# Generated by Django 4.2.5 on 2023-09-18 00:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 17, 0, 39, 33, 245582)),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 17, 0, 39, 33, 245814)),
        ),
    ]
