# Generated by Django 4.2.5 on 2023-09-18 00:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_project_due_date_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 17, 0, 17, 10, 385180)),
        ),
        migrations.AlterField(
            model_name='project',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 17, 0, 17, 10, 384181)),
        ),
    ]
