# Generated by Django 4.2.5 on 2023-09-18 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_project_options_alter_project_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 17, 15, 31, 23, 10990)),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 17, 15, 31, 23, 11822)),
        ),
    ]
